[package]
name = "server"
version = "0.1.0"
authors = ["Jesper Axelsson <jesperaxe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"


pretty_env_logger = "0.3"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
futures="*"
log = "0.4"

sqlx = { version = "0.2", default-features = false, features = [ "runtime-tokio", "macros", "postgres" ] }